name: Build and Push
on:
  push:
    branches:
      - master
      - production
    paths-ignore:
      - 'client/**'
      - '.github/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: docker:19.03.5
    services:
      image: docker:19.03.5-dind
    steps:
      - uses: actions/checkout@v2
      - run: apk add python3
      - run: pip3 install awscli
      - run: docker build --compress -t $ECR_REPO:$CI_COMMIT_SHORT_SHA .
      - run: $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - run: docker push $ECR_REPO:$CI_COMMIT_SHORT_SHA
      - run: docker tag $ECR_REPO:$CI_COMMIT_SHORT_SHA $ECR_REPO:latest
      - run: docker push $ECR_REPO:latest