name: Build and Push
on:
  push:
    branches:
      - master
      - production
    paths-ignore:
      - 'client/**'
      - '.github/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: docker:19.03.5
    services:
      image: docker:19.03.5-dind
    steps:
      - uses: actions/checkout@v2
      - env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          - apk add python3
          - pip3 install awscli
          - docker build --compress -t $ECR_REPO:$IMAGE_TAG .
          - $(aws ecr get-login --no-include-email --region ap-southeast-1)
          - docker push $ECR_REPO:$IMAGE_TAG
          - docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
          - docker push $ECR_REPO:latest