name: Build and Push
on:
  push:
    branches:
      - master
      - production
    paths-ignore:
      - 'client/**'
      - '.github/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: docker:19.03.5
    services:
      image: docker:19.03.5-dind
    steps:
      - run: echo "This job runs on commits being merged on master or production"