name: Terraform Staging Apply
on:
  push:
    branches:
      - master
      - production
    paths-ignore:
      - 'client/**'
      - '.github/**'

jobs:
  terraform-staging-apply:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:0.14.3
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Staging Apply
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: ${{ github.sha }}
          TF_VAR_db_username: ${{ secrets.TF_VAR_db_username }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_rails_master_key: ${{ secrets.TF_VAR_rails_master_key }}
        run: |
          cd deploy/
          export TF_VAR_ecr_image_api=$ECR_REPO:$IMAGE_TAG
          terraform init
          terraform workspace select staging
          terraform apply -auto-approve