name: Terraform Staging Apply
on:
  push:
    branches:
      - master
      - production
    paths-ignore:
      - 'client/**'
      - '.github/**'

jobs:
  terraform-staging-apply:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:0.14.3
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Staging Apply
        env:
          ECR_REPO: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: ${{ github.sha }}
          DB_USERNAME: ${{ secrets.staging.TF_VAR_db_username }}
          DB_PASSWORD: ${{ secrets.staging.TF_VAR_db_password }}
          RAILS_MASTER_KEY: ${{ secrets.staging.TF_VAR_rails_master_key }}
        run: |
          cd deploy/
          export TF_VAR_ecr_image_api=$ECR_REPO:$IMAGE_TAG
          export TF_VAR_db_username=$DB_USERNAME
          export TF_VAR_db_password=$DB_PASSWORD
          export TF_VAR_rails_master_key=$RAILS_MASTER_KEY
          echo $TF_VAR_rails_master_key
          echo $TF_VAR_db_password
          terraform init
          terraform workspace select staging
          terraform apply -auto-approve