name: Terraform Staging Plan
on:
  pull_request:
    paths:
      - 'deploy/**' # Do not run this action when nothing in deploy is changed

jobs:
  terraform-staging-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:0.14.3
    steps:
      - run: echo "This job runs on Pull Request creation with terraform code changes"