name: Test API on Pull Requests
on:
  pull_request:
    paths-ignore:
      - 'client/**'

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: docker:19.03.5
    services:
      image: docker:19.03.5-dind
    steps:
      - run: apk add --no-cache docker-compose
      - run: docker-compose -f docker-compose.test.yml run --rm api rspec